# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'WeexDev' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeexDev
  pod 'WeexSDK', '~> 0.26.0'
  pod 'WXDevtool', '~> 0.24.0', :configurations => ['Debug']
  pod 'SDWebImage', '~> 5.0.6'
  pod 'SDCycleScrollView', '~> 1.80'
end
